<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>nullable</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MetaFac.Threading.Channels\MetaFac.Threading.Channels.csproj" />
    <ProjectReference Include="..\MetaFac.Threading.Disruptor\MetaFac.Threading.Disruptor.csproj" />
    <ProjectReference Include="..\MetaFac.Threading\MetaFac.Threading.csproj" />
  </ItemGroup>

</Project>
